//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class approval
    {
        public int APID { get; set; }
        public int LID { get; set; }
        public string status { get; set; }
        public string ManagerID { get; set; }
    
        public virtual leav leav { get; set; }
        public virtual employee employee { get; set; }
    }
}
