//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class duty_leave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public duty_leave()
        {
            this.trackings = new HashSet<tracking>();
        }
    
        public int DLID { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan appointmentTime { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
        public string location { get; set; }
        public string EID { get; set; }
        public string purpose { get; set; }
    
        internal virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<tracking> trackings { get; set; }
    }
}
