//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ebuilderEntities : DbContext
    {
        public ebuilderEntities()
            : base("name=ebuilderEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<approval> approvals { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<duty_leave> duty_leave { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<leav> leavs { get; set; }
        public virtual DbSet<leave_type> leave_type { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<tracking> trackings { get; set; }
    }
}
