//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class leav
    {
        public int LID { get; set; }
        public System.DateTime date { get; set; }
        public string reason { get; set; }
        public string category { get; set; }
        public string EID { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
