//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class leav
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public leav()
        {
            this.approvals = new HashSet<approval>();
        }
    
        public int LID { get; set; }
        public System.DateTime date { get; set; }
        public string reason { get; set; }
        public string leaveCategory { get; set; }
        public string jobCategory { get; set; }
        public string EID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<approval> approvals { get; set; }
        internal virtual employee employee { get; set; }
        internal virtual leave_type leave_type { get; set; }
    }
}
