//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public notification()
        {
            this.employees = new HashSet<employee>();
        }
    
        public int NID { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string content { get; set; }
    
        internal virtual ICollection<employee> employees { get; set; }
    }
}
