//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracking
    {
        public int TRID { get; set; }
        public float longitude { get; set; }
        public float latitude { get; set; }
        public System.TimeSpan time { get; set; }
        public int DLID { get; set; }
    
        public virtual duty_leave duty_leave { get; set; }
    }
}
